version: '3.3'

services:
    nginx:
        image: nginx
        container_name: "${DOCKER_PREFIX}-nginx"
        restart: unless-stopped
        tty: true
        ports:
            - 8080:80
        depends_on:
            - php-fpm
        volumes:
            - ./www:/var/www
            - ./images/nginx/local.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build:
            context: .
            dockerfile: images/php-fpm/Dockerfile
        container_name: "${DOCKER_PREFIX}-php-fpm"
        volumes:
            - ./www:/var/www
            - ./images/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
        tty: true
        ports:
            - 9000:9000
            - 6001:6001
        environment:
            SERVICE_NAME: php-fpm
            SERVICE_TAGS: dev
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql:5.7
        container_name: "${DOCKER_PREFIX}-mysql"
        restart: unless-stopped
        tty: true
        ports:
            - 33061:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_USER=${MYSQL_DB_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DB_DATABASE}
            - SERVICE_NAME:mysql
            - SERVICE_TAGS:dev
    redis:
        image: redis:latest
        container_name: "${DOCKER_PREFIX}-redis"
        restart: always
        hostname: redis
        volumes:
            - ./images/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
